export const paths = {
  home: '/',
  login: '/login',
  dashboard: {
    base: '/dashboard',
    proyecto: (id: number | string) => `/dashboard/proyecto/${id}`,
    actividad: (id: number | string) => `/dashboard/actividad/${id}`,
  },
  perfil: '/perfil',
  notificaciones: '/notificaciones',
  recursosHumanos: '/recursos-humanos',
  pgd: {
    base: '/pgd',
    dashboard: '/pgd/dashboard',
    oei: '/pgd/oei',
    aei: '/pgd/aei',
    ogd: '/pgd/ogd',
    oegd: '/pgd/oegd',
    ae: '/pgd/ae',
    proyectos: '/pgd/proyectos',
  },
  poi: {
    base: '/poi',
    actividades: '/poi', // Lista de actividades en POI
    proyectos: {
      base: '/poi/proyectos',
      nuevo: '/poi/proyectos/nuevo',
      detalles: (id: number | string) => `/poi/proyectos/${id}`,
      editar: (id: number | string) => `/poi/proyectos/${id}/editar`,
      cronograma: (id: number | string) => `/poi/proyectos/${id}/cronograma`,
      daily: (id: number | string) => `/poi/proyectos/${id}/daily`,
      backlog: (id: number | string) => `/poi/proyectos/${id}/backlog`,
      tablero: (id: number | string) => `/poi/proyectos/${id}/tablero`,
      sprints: (id: number | string) => `/poi/proyectos/${id}/sprints`,
      epicas: (id: number | string) => `/poi/proyectos/${id}/epicas`,
      requerimientos: (id: number | string) => `/poi/proyectos/${id}/requerimientos`,
      documentos: (id: number | string) => `/poi/proyectos/${id}/documentos`,
      actas: (id: number | string) => `/poi/proyectos/${id}/actas`,
      actaConstitucion: (id: number | string) => `/poi/proyectos/${id}/actas/constitucion`,
      actaConstitucionNueva: (id: number | string) => `/poi/proyectos/${id}/actas/constitucion/nueva`,
      actaReunionNueva: (id: number | string) => `/poi/proyectos/${id}/actas/reunion/nueva`,
      actaReunion: (id: number | string, actaId: number | string) => `/poi/proyectos/${id}/actas/reunion/${actaId}`,
      // Informes de Sprint
      informes: (id: number | string) => `/poi/proyectos/${id}/informes`,
      informeDetalle: (id: number | string, informeId: number | string) => `/poi/proyectos/${id}/informes/${informeId}`,
      informeNuevo: (id: number | string) => `/poi/proyectos/${id}/informes/nuevo`,
    },
    subproyectos: {
      base: '/poi/subproyectos',
      detalles: (id: number | string) => `/poi/subproyectos/${id}`,
      editar: (id: number | string) => `/poi/subproyectos/${id}/editar`,
      cronograma: (id: number | string) => `/poi/subproyectos/${id}/cronograma`,
      daily: (id: number | string) => `/poi/subproyectos/${id}/daily`,
      backlog: (id: number | string) => `/poi/subproyectos/${id}/backlog`,
      tablero: (id: number | string) => `/poi/subproyectos/${id}/tablero`,
      sprints: (id: number | string) => `/poi/subproyectos/${id}/sprints`,
      epicas: (id: number | string) => `/poi/subproyectos/${id}/epicas`,
      requerimientos: (id: number | string) => `/poi/subproyectos/${id}/requerimientos`,
      documentos: (id: number | string) => `/poi/subproyectos/${id}/documentos`,
      actas: (id: number | string) => `/poi/subproyectos/${id}/actas`,
      actaConstitucion: (id: number | string) => `/poi/subproyectos/${id}/actas/constitucion`,
      actaConstitucionNueva: (id: number | string) => `/poi/subproyectos/${id}/actas/constitucion/nueva`,
      actaReunionNueva: (id: number | string) => `/poi/subproyectos/${id}/actas/reunion/nueva`,
      actaReunion: (id: number | string, actaId: number | string) => `/poi/subproyectos/${id}/actas/reunion/${actaId}`,
      informes: (id: number | string) => `/poi/subproyectos/${id}/informes`,
      informeDetalle: (id: number | string, informeId: number | string) => `/poi/subproyectos/${id}/informes/${informeId}`,
      informeNuevo: (id: number | string) => `/poi/subproyectos/${id}/informes/nuevo`,
    },
    // DEPRECATED: Sistema antiguo - usar poi.proyectos en su lugar
    proyecto: {
        deprecated: true as const,
        redirectTo: '/poi/proyectos',
        detalles: '/poi/proyecto/detalles',
        documentos: '/poi/proyecto/documentos',
        actas: '/poi/proyecto/actas',
        actasNueva: '/poi/proyecto/actas/nueva',
        requerimientos: '/poi/proyecto/requerimientos',
        cronograma: '/poi/proyecto/cronograma',
        backlog: {
            base: '/poi/proyecto/backlog',
            tablero: '/poi/proyecto/backlog/tablero',
            dashboard: '/poi/proyecto/backlog/dashboard',
        },
    },
    actividad: {
        base: '/poi/actividad',
        detalles: '/poi/actividad/detalles',
        lista: '/poi/actividad/lista',
        tablero: '/poi/actividad/tablero',
        dashboard: '/poi/actividad/dashboard',
        byId: (id: number | string) => `/poi/actividad/${id}`,
        // Informes de Actividad
        informes: '/poi/actividad/informes',
        informeDetalle: (informeId: number | string) => `/poi/actividad/informes/${informeId}`,
        informeNuevo: '/poi/actividad/informes/nuevo',
    }
  },
  aprobaciones: {
    base: '/aprobaciones',
    pendientes: '/aprobaciones/pendientes',
  },
};
